import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidePane from "./_components/SidePane";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="p-2 min-h-screen grid ">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-black antialiased grid grid-cols-[250px_1fr] grid-rows-1 h-full`}>
        <SidePane />
        <main className=" bg-neutral-900/70 h-full w-full rounded border border-zinc-500/30">
          {children}
        </main>
      </body>
    </html>
  );
}
